export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_PLAYLISTS: "SET_PLAYLISTS",
    SET_USER: "SET_USER",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_PLAYING: "SET_PLAYING",
    SET_PLAYER_STATE: "SET_PLAYER_STATE",
    SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
    SET_SEARCH_RESULT: "SET_SEARCH_RESULT",
    SET_USER_PLAYLISTS: "SET_USER_PLAYLISTS",
    SET_USER_INFO: "SET_USER_INFO",
    SET_RECENTLY_PLAYED: "SET_RECENTLY_PLAYED",
    SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
    SET_REFRESH_TOKEN: "SET_REFRESH_TOKEN",
    AUDIO_ANALYSER_OPTIONS: "audio-analyser-options",
    VISUALIZER_OPTIONS: "visualizer-options",
    SET_VISUALIZER: "SET_VISUALIZER",
    SET_PLAYER_TRACKS: "SET_PLAYER_TRACKS",
    SET_PLAYER_CURRENT_TRACK: "SET_PLAYER_CURRENT_TRACK",
    SET_PLAYER_PROGRESS: "SET_PLAYER_PROGRESS",
    SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
    
  };

